mode = "dark"
accent = "#ff71ce"
selection = "#2c1c38"
muted = "#4b3260"
background = "#1a0b2e"
dark_background = "#120621"
darker_background = "#090311"
lighter_background = "#2b1448"
foreground = "#e0cce5"
dark_foreground = "#7a5c8e"
light_foreground = "#eedef2"
bright_foreground = "#ffffff"
red = "#ff71ce"
yellow = "#f3f57a"
orange = "#ffb07c"
green = "#01cdfe"
cyan = "#05ffa1"
blue = "#b967ff"
magenta = "#ff71ce"
brown = "#8a5a73"
bright_red = "#ff93da"
bright_yellow = "#f7f8a1"
bright_green = "#3dffc7"
bright_cyan = "#4dffbc"
bright_blue = "#cf96ff"
bright_magenta = "#ff93da"
