# X64 Studios Edition - Hyprland Config
# Esta configuración es el lienzo en blanco oficial para X64 Studios.
# Será actualizada mediante x64-update en el futuro.

# Configuraciones básicas (Para arrancar sin errores)
monitor=,preferred,auto,auto
exec-once = waybar -c ~/.config/waybar-x64/config
