mode = "dark"
accent = "#00ff41"
selection = "#051a08"
muted = "#0a3311"
background = "#030804"
dark_background = "#010502"
darker_background = "#000000"
lighter_background = "#051407"
foreground = "#8ceb9e"
dark_foreground = "#3b854a"
light_foreground = "#b3f0c1"
bright_foreground = "#ffffff"
red = "#ff3333"
yellow = "#e6d600"
orange = "#e68a00"
green = "#00ff41"
cyan = "#00e6a8"
blue = "#0066ff"
magenta = "#b300ff"
brown = "#594322"
bright_red = "#ff6666"
bright_yellow = "#ffee33"
bright_green = "#33ff66"
bright_cyan = "#33ffc2"
bright_blue = "#3385ff"
bright_magenta = "#c633ff"
