mode = "dark"
accent = "#00f0ff"
selection = "#101625"
muted = "#252b45"
background = "#050608"
dark_background = "#020304"
darker_background = "#010102"
lighter_background = "#0a0c12"
foreground = "#d1d5e5"
dark_foreground = "#5c668a"
light_foreground = "#e4e7f2"
bright_foreground = "#ffffff"
red = "#ff007f"
yellow = "#ffea00"
orange = "#ff5500"
green = "#00ffcc"
cyan = "#00f0ff"
blue = "#7000ff"
magenta = "#b300ff"
brown = "#8b4513"
bright_red = "#ff3399"
bright_yellow = "#ffee33"
bright_green = "#33ffd6"
bright_cyan = "#33f3ff"
bright_blue = "#8c33ff"
bright_magenta = "#c433ff"
