mode = "dark"
accent = "#ffffff"
selection = "#1f1f1f"
muted = "#333333"
background = "#0a0a0a"
dark_background = "#050505"
darker_background = "#020202"
lighter_background = "#141414"
foreground = "#cccccc"
dark_foreground = "#666666"
light_foreground = "#e6e6e6"
bright_foreground = "#ffffff"
red = "#999999"
yellow = "#aaaaaa"
orange = "#888888"
green = "#bbbbbb"
cyan = "#dddddd"
blue = "#999999"
magenta = "#aaaaaa"
brown = "#555555"
bright_red = "#bbbbbb"
bright_yellow = "#cccccc"
bright_green = "#dddddd"
bright_cyan = "#eeeeee"
bright_blue = "#bbbbbb"
bright_magenta = "#cccccc"
